# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Automate Api Test

on:
  push:
    branches: [ "main" ]

jobs:

  Api-Test:
    strategy:
      matrix:
        os: [ "ubuntu-latest", "macos-latest" ]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Install dependencies
      run: go get .

    - name: Build
      run: go build

    - name: Run Api
      run: ${{github.workspace}}/A-Simple-Api-Go-Fiber &

    - if: matrix.os == 'ubuntu-latest'
      name: Install Postman CLI Linux
      run: |
        curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
    - if: matrix.os == 'macOS-latest'
      name: Install Postman CLI MacOS
      run: |
        curl -o- "https://dl-cli.pstmn.io/install/osx_64.sh" | sh
    - name: Login to Postman CLI
      run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
    - name: Run API tests
      run: |
        postman collection run "7779863-874f5270-9a2e-448e-a963-87f8b9b0cbbd" -e "7779863-a2096246-922a-440d-9863-d540e8ff461d"
